
/*
 * Main.eq
 * Generated by Eqela Studio 2.0b7.4
 */

public class Main : LayerWidget
{
	public void initialize() {
		base.initialize();
		set_size_request_override(px("50mm"), px("70mm"));
		add(CanvasWidget.for_colors(Color.instance("red"), Color.instance("black")));
		add(LabelWidget.for_string("SANDOVAL").set_font(Theme.font().modify("6mm bold color=white outline-color=black")));
		set_draw_color(Color.instance("blue"));
	}
}

